spring:
  boot:
    admin:
      client:
        url: http://localhost:1112/
       
    
  cloud:
    compatibility-verifier:
      enabled: false
       
    

    
management:
  endpoints:
    web:
      exposure:
        include: '*'
    
