spring:
  application:
    name: GREETAPI
  boot:
    admin:
      client:
        url: http://localhost:6666/
       
    

    
management:
  endpoints:
    web:
      exposure:
        include: '*'
